config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'pages#home', as: :authenticated_root
  end

  root to: "pages#welcome"

  devise_for :users

  resources :courses do
    collection do
      get 'all', to: "courses#all"
    end
    resources :slides do
      collection do
        get 'overview', to: "slides#overview"
      end
    end
  end

  resources :slides do
    resources :notes do
      member do
        put 'like' => 'notes#upvote'
        put 'dislike' => 'notes#downvote'
      end
    end
  end

  resources :posts
  resources :polls, only: [:new, :create, :destroy]
  
  resources :user_courses, except: [:show, :edit, :update]

  get 'home' => 'pages#home', as: 'home'
  get 'users/:id' => 'users#show', as: 'user'
  get 'aboutus' => 'pages#aboutus', as: 'aboutus'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'terms' => 'pages#terms', as: 'terms'
  get 'privacy' => 'pages#privacy', as: 'privacy'
  get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
  get 'admininfo' => 'pages#admininfo', as: 'admininfo'
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :slide

  validates :comment, presence: true, length: { minimum: 1, maximum: 2500 }

  def score
  	self.get_upvotes - self.get_downvotes
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :note_params, only:[:create, :update]
  before_action :find_slide
  before_action :find_note, only: [:edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  
  def index
  end

  def new
  	@note = Note.new
  end

  def create
  	@note = Note.new(note_params)
  	@note.slide_id = @slide.id
  	@note.user_id = current_user.id
    if current_user.notes.where(:slide_id => @slide).size < 1
  	  if @note.save
        @note.slide.update(:amount_of_notes => @note.slide.notes.size)
  	    redirect_to :back        
  	  else
  	    redirect_to :back
        flash[:alert] = "Please make sure your note contains between 1-2500 characters"
  	  end
    else
      redirect_to :back
      flash[:alert] ="Only 1 note per slide allowed. Please edit your existing note"
    end
  end

  def edit
    session[:return_to] ||= request.referer
  end

  def update
    if @note.update(note_params)
      redirect_to session.delete(:return_to)
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    @note.slide.decrement!(:amount_of_notes)
    redirect_to :back
  end

  def upvote
    @note.upvote_from current_user
    if @note.vote_registered?
      @note.user.increment!(:score)
      @note.user.check_level
    end
    redirect_to :back
  end

  def downvote
    @note.downvote_from current_user
    if @note.vote_registered?
      @note.user.decrement!(:score)
      @note.user.check_level
    end
    redirect_to :back
  end

  private

    def note_params
      params.require(:note).permit(:comment)
    end

    def find_slide
      @slide = Slide.find(params[:slide_id])
    end

    def find_note
      @note = @slide.notes.find(params[:id])
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for([@slide, @slide.notes.build]) do |f| %>
  <%= f.input :comment, label: 'Add a note', input_html: {:rows => 10} %>
  <%= f.button :submit %>
<% end %>

app/views/notes/_myNote.html.erb
<% @slides.order(:id => :asc).each do |slide| %>
  <h3>My notes</h3>
  <% if slide.notes.where(:user_id => current_user).empty? %>

    <%= simple_form_for([slide, slide.notes.build]) do |f| %>

      <%= f.input :comment, label: "You currently have no notes on this slide, add one here:", required: false, input_html: {:rows => 10}, placeholder: 'Add HTML tags to style your note: <h1>Heading 1</h1>, <b>bold</b>, <i>Italic</i>,...' %>
      <%= f.button :submit, :class => "btn btn-default" %>

    <% end %>
  <% end %>


  <%= render slide.notes.where(:user_id => current_user) %>

  <hr style="border-color: #ccc">

  <h3>Top notes</h3>
  
  <%= render slide.notes.where.not(:user_id => current_user).order(:cached_votes_score => :desc) %>


<% end %>

app/views/notes/_note.html.erb
 <div class="panel panel-default">
   <div class="panel-body">
    <small><strong id="link"><%= link_to note.user.first_name, user_path(note.user) %></strong> <span class="<%= note.user.check_level %>"><%= note.user.level %></span></small>

    <span class="inline pull-right">
    <small><i>Posted <%= time_ago_in_words(note.created_at) %> ago &nbsp; &nbsp;</i> </small>

    <div class="btn-group inline pull-right">
      <%= link_to like_slide_note_path(note.slide, note), method: :put, class: "btn btn-success btn-sm" do %>
	    <%= note.get_upvotes.size %>
	    <span class="glyphicon glyphicon-thumbs-up"></span>
	  <% end %>

	  <%= link_to dislike_slide_note_path(note.slide, note), method: :put, class: "btn btn-default btn-sm" do %>
	    <%= note.get_downvotes.size %>
	    <span class="glyphicon glyphicon-thumbs-down"></span>
	  <% end %>
	</div>

	</span>

    <p style="white-space: pre-wrap;"><%= sanitize note.comment %></p>
	<%#= note.slide_id %>
	<%#= note.id %>

	<% if note.user_id == current_user.id %>
	  <%= link_to "Edit", edit_slide_note_path(note.slide_id, note.id) %>
	  <%= link_to "Delete", slide_note_path(note.slide_id, note.id), method: :delete, data: { confirm: "are you sure you want to delete this note?"} %>
	<% end %>

	<% if current_user.admin? %>
	  <%= link_to "Edit", edit_slide_note_path(note.slide_id, note.id) %>
	  <%= link_to "Delete", slide_note_path(note.slide_id, note.id), method: :delete, data: { confirm: "are you sure you want to delete this note?"} %>
	<% end %>

  </div>
</div>

app/views/notes/edit.html.erb
<p>Edit note</p>

<%= simple_form_for([@slide, @note]) do |f| %>
  <%= f.input :comment, input_html: {:rows => 20}, placeholder: 'Add HTML tags to style your note: <h1>Heading 1</h1>, <b>bold</b>, <i>Italic</i>,...' %>
  <%= f.button :submit %>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>