config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'pages#home', as: :authenticated_root
  end

  root to: "pages#welcome"

  devise_for :users

  resources :courses do
    collection do
      get 'all', to: "courses#all"
    end
    resources :slides do
      collection do
        get 'overview', to: "slides#overview"
      end
    end
  end

  resources :slides do
    resources :notes do
      member do
        put 'like' => 'notes#upvote'
        put 'dislike' => 'notes#downvote'
      end
    end
  end

  resources :posts
  resources :polls, only: [:new, :create, :destroy]
  
  resources :user_courses, except: [:show, :edit, :update]

  get 'home' => 'pages#home', as: 'home'
  get 'users/:id' => 'users#show', as: 'user'
  get 'aboutus' => 'pages#aboutus', as: 'aboutus'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'terms' => 'pages#terms', as: 'terms'
  get 'privacy' => 'pages#privacy', as: 'privacy'
  get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
  get 'admininfo' => 'pages#admininfo', as: 'admininfo'
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :course_params, only: [:create, :update]
  before_action :find_params, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :adminfunc, only: [:new, :create, :edit, :update, :destroy]

  def index
  	@courses = Course.all
    @user = current_user
    @categories = Category.all
  end

  def new
  	@course = Course.new
  end

  def create
  	@course = Course.new(course_params)
  	if @course.save
  	  redirect_to courses_path
  	else
  	  render 'new'
  	end
  end

  def edit
  end

  def update
  	if @course.update(course_params)
  	  redirect_to courses_path
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	@course.destroy
  	redirect_to courses_path
  end

  def all
    @courses = Course.all
    @categories = Category.all
  end

  private

    def course_params
      params.require(:course).permit(:name, :description)
    end

    def find_params
      @course = Course.find(params[:id])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/courses/all.html.erb
<h1 class="page-header"><span class="glyphicon glyphicon-plus"></span> Manage Curriculum</h1>

<% @courses.each do |course| %>
  <h3><strong><%= course.name %></strong></h3>

	  <% if current_user.user_courses.where(course_id: course.id).first.nil? %>
	    <%#= link_to "Add to My courses", user_courses_path(user: current_user, course_id: course.id), class: "btn btn-success", method: :post %>
	    <%#= current_user.courses.size %>

 		<%= link_to "<span class=\"glyphicon glyphicon-plus\"></span>&nbsp; Enroll".html_safe, user_courses_path(user: current_user, course_id: course.id), method: :post, class: "btn btn-success" ,style: "color: white;" %>
	  <%else%>
	    <%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>&nbsp; Withdraw".html_safe, user_course_path(course.user_courses.where(user_id: current_user).first.id), method: :delete, data: { confirm: "Are you sure you want to withdraw from this course? (Your notes will not be deleted from the course)"}, class: "btn btn-default" %><br>
	  <% end %>

    <% if current_user.admin? %>
      <%= link_to "Edit", edit_course_path(course) %>
      <%= link_to "Delete", course_path(course), method: :delete, data: { confirm: "Are you sure you want to delete this course?"} %>
    <% end %>


    <hr>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<h1 class="page-header"><span class="glyphicon glyphicon-book"></span> My Courses</h1>

<% if @user.courses.empty? %>
  <h3>You dont have any courses at the moment</h3>
  <p><%= link_to "Click here", all_courses_path %> to enroll in a course and get started!</p>
<% else%>

  <% @user.courses.each do |course| %>
    <h3><strong><%= course.name %></strong></h3>
	    <p><%= sanitize course.description %></p>
	    
  	  <%= link_to "Slides Overview", overview_course_slides_path(course, category: 1), class: "btn btn-primary" %>

	    <% course.available_categories.each do |category| %>
	      <%#= link_to "H#{category.chapter}", overview_course_slides_path(course, :category => category), class: "btn btn-default"%>
	      <%#= link_to "h#{category.chapter}", course_slides_path(course, :category => category, :page => course.slides.index(course.slides.where(:category => category).first).to_i + 1) %>
	      <%= link_to "h#{category.chapter}", course_slides_path(course, category: category, page: 1), class: "btn btn-default" %>
	    <% end %>

	    <% if current_user.admin? %>
	      <%= link_to "Edit", edit_course_path(course) %>
	      <%= link_to "Delete", course_path(course), method: :delete, data: { confirm: "Are you sure you want to delete this course?"} %>
	    <% end %>

	    <hr>

  <% end %>
<% end %>

app/views/courses/new.html.erb
<h3>New Course</h3>

<%= render 'form' %>