config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'pages#home', as: :authenticated_root
  end

  root to: "pages#welcome"

  devise_for :users

  resources :courses do
    collection do
      get 'all', to: "courses#all"
    end
    resources :slides do
      collection do
        get 'overview', to: "slides#overview"
      end
    end
  end

  resources :slides do
    resources :notes do
      member do
        put 'like' => 'notes#upvote'
        put 'dislike' => 'notes#downvote'
      end
    end
  end

  resources :posts
  resources :polls, only: [:new, :create, :destroy]
  
  resources :user_courses, except: [:show, :edit, :update]

  get 'home' => 'pages#home', as: 'home'
  get 'users/:id' => 'users#show', as: 'user'
  get 'aboutus' => 'pages#aboutus', as: 'aboutus'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'contact' => 'pages#contact', as: 'contact'
  get 'terms' => 'pages#terms', as: 'terms'
  get 'privacy' => 'pages#privacy', as: 'privacy'
  get 'leaderboard' => 'pages#leaderboard', as: 'leaderboard'
  get 'admininfo' => 'pages#admininfo', as: 'admininfo'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :slides

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :slides, dependent: :destroy
  has_many :user_courses
  has_many :users, through: :user_courses

  cattr_accessor :current_user

  def available_categories
  	category_array = []
  	self.slides.each do |slide|
  	  unless slide.category.in?(category_array)
  	    category_array.push(slide.category)
  	  end
  	end
    category_array.sort
    return category_array
  end


end

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :slide

  validates :comment, presence: true, length: { minimum: 1, maximum: 2500 }

  def score
  	self.get_upvotes - self.get_downvotes
  end

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :stringanswer
  validates :feedback, length: { maximum: 10000 }
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :course
  belongs_to :category
  has_many :notes, dependent: :destroy
  mount_uploader :image, ImageUploader


end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_many :notes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :user_courses
  has_many :courses, through: :user_courses
  has_many :polls

  validates_format_of :email, with: /@ugent.be/, message: "Only @ugent.be email allowed"


  def give_user_score
    @my_array = Array.new
  	self.notes.each do |note|
  	  @my_array.push(note.score)
  	end
    self.score = @my_array.sum
  end

  def first_name
  	@name_regex = /^([^\.@]+)\.*([^@]*)/
  	first, last = self.email.match(@name_regex).captures
  	return first.titleize
  end

  def last_name
  	@name_regex = /^([^\.@]+)\.*([^@]*)/
  	first, last = self.email.match(@name_regex).captures
  	return last.titleize
  end

  def check_level
    if self.score >= 20
      self.update(:level => "Doctoraatstudent")
      return "label label-success"
    elsif self.score >= 10
      self.update(:level => "Laureaat")
      return "label label-warning"
    elsif self.score >= 5
      self.update(:level => "Alumnus")
      return "label label-info"
    elsif self.score >= 0
      self.update(:level => "Student")
      return "label label-default"
    elsif self.score < 0
      self.update(:level => "Student")
      return "label label-danger"
    end
  end

  def likes_per_comment
    unless self.score.nil?
      return self.score.to_f/self.notes.size.to_f
    end
  end


end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :note_params, only:[:create, :update]
  before_action :find_slide
  before_action :find_note, only: [:edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  
  def index
  end

  def new
  	@note = Note.new
  end

  def create
  	@note = Note.new(note_params)
  	@note.slide_id = @slide.id
  	@note.user_id = current_user.id
    if current_user.notes.where(:slide_id => @slide).size < 1
  	  if @note.save
        @note.slide.update(:amount_of_notes => @note.slide.notes.size)
  	    redirect_to :back        
  	  else
  	    redirect_to :back
        flash[:alert] = "Please make sure your note contains between 1-2500 characters"
  	  end
    else
      redirect_to :back
      flash[:alert] ="Only 1 note per slide allowed. Please edit your existing note"
    end
  end

  def edit
    session[:return_to] ||= request.referer
  end

  def update
    if @note.update(note_params)
      redirect_to session.delete(:return_to)
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    @note.slide.decrement!(:amount_of_notes)
    redirect_to :back
  end

  def upvote
    @note.upvote_from current_user
    if @note.vote_registered?
      @note.user.increment!(:score)
      @note.user.check_level
    end
    redirect_to :back
  end

  def downvote
    @note.downvote_from current_user
    if @note.vote_registered?
      @note.user.decrement!(:score)
      @note.user.check_level
    end
    redirect_to :back
  end

  private

    def note_params
      params.require(:note).permit(:comment)
    end

    def find_slide
      @slide = Slide.find(params[:slide_id])
    end

    def find_note
      @note = @slide.notes.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:leaderboard, :home, :admin]
  before_action :adminfunc, only: [:admininfo]
  layout 'pages'
  
  def home
    @slides = Slide.all.where("amount_of_notes > ?", 1)
    @post = Post.last
    @number = @slides.all
    @users = User.all
    @user = User.last
    @notes = Note.all
    @ary = Array.new
    @my_array = Array.new
    @usernotes = current_user.notes

    render layout: 'application'
  end

  def welcome
    render layout: 'welcome'
  end

  def aboutus
  end

  def faq
  end

  def leaderboard
  	@users = User.all
  	@user = User.last
  	@notes = Note.all
  	@ary = Array.new
  	@my_array = Array.new
    @usernotes = current_user.notes

  	render layout: 'application'  
  end

  def admininfo
    @users = User.all.order(:id => :desc)
    @notes = Note.all
    @slides = Slide.all
    @polls = Poll.all


    render layout: 'application'
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :poll_params, only: [:create, :new]

  def new
    @poll = current_user.polls.build
  end

  def create
  	@poll = current_user.polls.build(poll_params)
  	if @poll.save
  	  redirect_to :back
  	  flash[:alert] = "De feedback is geregisteerd"
  	else
  	  redirect_to :back
   	  flash[:alert] = "Gelieve een antwoord te selecteren"
  	end
  end

  def destroy
  	current_user.polls.last.destroy
  	redirect_to :back
  end

  private

    def poll_params
      params.require(:poll).permit(:stringanswer, :feedback, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def resource_name
    :user
  end

  def resource_class 
     User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/user_courses_helper.rb
module UserCoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slidenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 0; margin: 0;">
          <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand"), root_path %>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">  
      <div class="col-sm-3 col-md-2 sidebar">
  	    <ul class="nav nav-sidebar">
          <li id="link"><%= link_to "<span class=\"glyphicon glyphicon-home\"></span>&nbsp; Home".html_safe, home_path %></li>
          <br>
  	      <li id="link"><%= link_to "<span class=\"
glyphicon glyphicon-book\"></span>&nbsp; My courses".html_safe, courses_path %></li>
          <li id="link"><%= link_to "<span class=\"glyphicon glyphicon-user\"></span>&nbsp; Profile".html_safe, user_path(current_user) %></li>
  	      <!--<li id="link"><%= link_to "<span class=\"glyphicon glyphicon-stats\"></span>&nbsp; Leaderboard".html_safe, leaderboard_path %></li>-->
          <li id="link"><%= link_to "<span class=\"glyphicon glyphicon-plus\"></span>&nbsp; Manage Curriculum".html_safe, all_courses_path %></li>
  	      <li id="link"><%= link_to "<span class=\"
glyphicon glyphicon-bell\"></span>&nbsp; News".html_safe, posts_path %></li>          
  	    </ul>
  	    <ul class="nav nav-sidebar" id="bottom-links">
  	  	  <li id="li-pages"><%= link_to 'About us', aboutus_path %></li>
          <li id="li-pages"><%= link_to 'Contact', contact_path %></li>
          <!--<li id="li-pages"><%#= link_to 'Faq', faq_path %></li>
          <li id="li-pages"><%#= link_to 'Privacy', privacy_path %></li>
          <li id="li-pages"><%#= link_to 'Terms', terms_path %></li>-->
          <li id="copyright">&copy Nicolaas Danneels <%= Time.now.year %></li>
  	    </ul>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div ="container">
          <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
          <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
        </div>
		    <%= yield %>
      </div>
    </div>
  </div>



</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slidenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand"), root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="col-sm-6 col-sm-offset-3">

  <div ="container">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
  </div>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slidenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 0; margin: 0;">
          <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand"), root_path %>
        </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

<div class="col-sm-8 col-md-offset-2" style="margin-top: 80px; margin-bottom: 65px;">

  <div ="container">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
  </div>
  <%= yield %>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container" style="text-align: center; padding-top: 10px; font-size: 12px;">
    <%= link_to "About", aboutus_path %> &nbsp
    <%#= link_to "Faq", faq_path %> &nbsp
    <%= link_to "Contact", contact_path %>&nbsp
    <%#= link_to "Terms", terms_path %>&nbsp
    <%#= link_to "Privacy", privacy_path %>
    <p style="font-size: 11px;">&copy Nicolaas Danneels <%= Time.now.year %></p>
  </div>
</nav>

</body>
</html>

app/views/layouts/slides.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slidenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #f5f5f5">

  <nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand"), root_path %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  
  <div class="col-sm-6" id="slides">
    <%= yield %>
  </div>

  <div class="col-sm-6" id="comments">

  <div class="container-fluid">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
  </div>

    <%= render 'notes/myNote' %>

  </div>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slidenote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="welcome_body">

<div class="hidden-xs hidden-sm">
<nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand", :class => "hidden-xs"), root_path %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= %>
          <span>
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), :html => { :class => 'form-horizontal', style: 'padding-top: 10px; padding-bottom: 0px; height: 0;' }) do |f| %>
            <div class="form-inline">
              <%= f.input :email, label: "Email: ",required: false, autofocus: true, :label_html => { style: "color: #bdc3c7; margin-right: 10px; font-size: 12px;"}, :input_html => {style: "margin-right: 40px; height: 25px; font-size: 12px;"} %>
              <%= f.input :password, required: false, label: "Password: ",:label_html => { style: "color: #bdc3c7; margin-right: 10px; font-size: 12px;"}, :input_html => {style: "margin-right: 40px; height: 25px; font-size: 12px;"} %>
              <%= f.input :remember_me,:label_html => { style: "color: #bdc3c7; font-size: 12px; margin-right: 50px;" } , as: :boolean if devise_mapping.rememberable? %>             
              <%= f.button :submit, "Log in", style: 'margin-right: 100px;', class: "btn btn-default btn-sm" %>           
            </div>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="col-sm-4 col-md-offset-1" style="margin-top: 10px;" id="welcome_message">
  <h1>Welcome to Slidenote!</h1>
  <p>Slidenote is an online tool to manage all your notes. Slidenote contains many courses filled with notes by you, and students in your class!</p>
  <p>To get started, fill in the Sign Up form. If you have already registered, you can simply log in. Remember that only Ugent Email is allowed to sign up.</p>
</div>

<div class="col-sm-4 col-md-offset-1" style="margin-top: 10px; margin-bottom: 65px;" id="welcome_signin">

  <div ="container">
    <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
  </div>
  <%= yield %>
</div>

</div>

<div class="hidden-lg hidden-md">
  <nav class="navbar navbar-default navbar-fixed-top" id="custom-bootstrap-menu">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#" style="padding: 0; margin: 0;">
          <%= link_to image_tag("slidenotelogo3.png", size: "115x47", alt: "Brand"), root_path %>
        </a>
      </div>
    </div>
  </nav>

  <h1>Welcome to Slidenote!</h1>
  <div class="alert alert-warning"><p>Please consider using this website on a bigger screen for a better experience</p></div>

  <%= render 'devise/sessions/new' %>
</div>


<nav class="navbar navbar-default navbar-fixed-bottom" id="footer">
  <div class="container" style="text-align: center; padding-top: 10px; font-size: 12px;">
    <%= link_to "About", aboutus_path %> &nbsp
    <%#= link_to "Faq", faq_path %> &nbsp
    <%= link_to "Contact", contact_path %>&nbsp
    <%#= link_to "Terms", terms_path %>&nbsp
    <%#= link_to "Privacy", privacy_path %>
    <p style="font-size: 11px;">&copy Nicolaas Danneels <%= Time.now.year %></p>
  </div>
</nav>

</body>
</html>

app/views/pages/aboutus.html.erb
<h1 class="page-header">About us</h1>

<p>Slidenote provides a new and easy way to manage all your notes. Moreover your notes can help other students!</p>

app/views/pages/admininfo.html.erb
<h1 class="page-header">Admin</h1>

<div class="col-md-6">
<h3>General Info</h3>
<ul>
  <li>Aantal users: <%= @users.size %></li>
  <li>Aantal notes: <%= @notes.size %></li>
  <li>Aantal slides: <%= @slides.size %></li>
</ul>
</div>

<div class="col-md-6">
  <h3>Feedback</h3>
  <p>aantal keren: "ja, kzou het gebruiken id les" <%= @polls.where(stringanswer: "ja, ik zou het gebruiken in de les").size %></p>
  <p>aantal keren: "ja, maar ik zou het niet gebruiken in de les" <%= @polls.where(stringanswer: "ja, maar ik zou het niet gebruiken in de les").size %></p>
  <p>aantal keren: "nee, ik zou dit niet gebruiken" <%= @polls.where(stringanswer: "nee, ik zou dit niet gebruiken").size %></p>
</div>


<h3>All users</h3>

<table class="table table-striped" idd="css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>User Id</th>
      <th>email</th>
      <th>sign in count</th>
      <th>Current sign in</th>
      <th>Last Sign in</th>
      <th>Notes</th>
      <th>Feedback</th>
      <th>Admin</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td></td>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><% unless user.sign_in_count.nil? %><%= user.sign_in_count %><% end %></td>
        <td><% unless user.current_sign_in_at.nil? %><%= time_ago_in_words(user.current_sign_in_at) %><% end %></td>
        <td><% unless user.last_sign_in_at.nil? %><%= time_ago_in_words(user.last_sign_in_at) %><% end %></td>    
        <td><% unless user.notes.size.nil? %><%= user.notes.size %><% end %></td>
        <td><% unless user.polls.last.nil? %><%= user.polls.last.feedback %><% end %></td>
        <td><%= user.admin %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/contact.html.erb
<h1 class='page-header'>Contact Us</h1>
<p>Feel free to contact us here: slidenotewebsite@gmail.com</p>

app/views/pages/faq.html.erb
<h1 class="page-header">F.a.q.</h1>

<h4>What is slidenote?</h4>
<p>Slidenote is a new way to keep track of all your notes. The cool thing is that your notes can help other people!</p>

app/views/pages/home.html.erb
<h1 class="page-header"><span class="glyphicon glyphicon-home"></span> Home</h1>


<div class="col-md-6">
  <div class="media">
    <h2>Latest News</h2>
    <hr>
    <h4><%= @post.title %></h4>
    <p style="white-space: pre-wrap;"><%= @post.body %></p>
  </div>

  <div class="alert alert-success">
    <% if current_user.polls.size == 0 %>
      <%= render 'polls/new' %>
    <% else %>
      <br>
      <h2>Bedankt voor de feedback!</h2>
      <p><%= link_to "Vul feedback opnieuw in", poll_path(current_user.polls.last), method: :delete, data: { confirm: "Uw vorige feedback wordt verwijderd, bent u zeker?"} %></p>
    <% end %>
  </div>
</div>


<div class="col-md-6">
  <h2 style="text-align: center"><span class="glyphicon glyphicon-stats"></span> Leaderboard</h2>
  <hr>

  <table class="table table-striped" idd="css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <!--<th>Last name</th>-->
      <th>Level</th>
      <th>Score</th>
      <th>Latest note</th>
    </tr>
  </thead>
  <tbody>
    <% @users.order(:score => :desc).limit(5).each do |user| %>
      <tr>

        <td></td>
        <td id="link"><%= link_to user.first_name, user_path(user) %></td>
        <!--<td><%= user.last_name %></td>-->        
        <td><span class="<%= user.check_level %>"><%= user.level %></span></td>
        <td><strong><%= user.score %></strong></td>
        <td>
          <% unless user.notes.last.nil? %>
            <%= time_ago_in_words(user.notes.last.created_at) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <h2 style="text-align: center"><span class="glyphicon glyphicon-fire"></span> Most discussed</h2>
  
  <hr>
  <table class="table table-striped" idd="css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>Slide</th>
      <th>Course</th>
      <th>Chapter</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @slides.order(:amount_of_notes => :desc).limit(5).each do |slide| %>
      <tr>
        <td></td>
        <td><%= link_to "View slide", course_slides_path(slide.course, :category => slide.category,:page => slide.course.slides.where(:category => slide.category).order(:id => :asc).index(slide).to_i + 1) %></td>
        <td><%= slide.course.name %></td>
        <td><strong><%= slide.category.chapter %></strong></td>
        <td><%= slide.amount_of_notes %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

</div>

app/views/pages/leaderboard.html.erb
<h1 class="page-header"><span class="glyphicon glyphicon-stats"></span> Leaderboard</h1>

<h3>Top 5 Most valuable users</h3>

<table class="table table-striped" idd="css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <!--<th>Last name</th>-->
      <th>Level</th>
      <th>Score</th>
      <th>Latest note</th>
    </tr>
  </thead>
  <tbody>
    <% @users.order(:score => :desc).limit(5).each do |user| %>
      <tr>

        <td></td>
        <td id="link"><%= link_to user.first_name, user_path(user) %></td>
        <!--<td><%= user.last_name %></td>-->        
        <td><span class="<%= user.check_level %>"><%= user.level %></span></td>
        <td><strong><%= user.score %></strong></td>
        <td>
          <% unless user.notes.last.nil? %>
            <%= time_ago_in_words(user.notes.last.created_at) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<!--
<h3>Best comments</h3>

<table class="table table-striped" idd="css-serial">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last name</th>
      <th>Comment</th>
      <th>Total Score</th>
    </tr>
  </thead>
  <tbody>
    <% @notes.order("cached_votes_score DESC").limit(5).each do |note| %>
      <tr>

        <td></td>
        <td><%= note.user.first_name %></td>
        <td><%= note.user.last_name %></td>
        <td><%= note.comment %></td>
        <td><%= note.cached_votes_score %></td>      
      </tr>
    <% end %>
  </tbody>
</table>
-->

app/views/pages/privacy.html.erb
<h1 class="page-header">Privacy</h1>

app/views/pages/terms.html.erb
<h1 class="page-header">Terms</h1>

app/views/pages/welcome.html.erb
<%= render 'devise/registrations/new' %>